spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never
  flyway:
    validate-on-migrate: true
    baseline-description: "initial migration"
    baseline-version: 0
    placeholders:
      ADMIN_USERNAME: ${PROD_ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: '${PROD_ADMIN_PASSWORD_HASH}'

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: error

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION_TIME}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION_TIME}
