spring:
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: never
  flyway:
    placeholders:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: '${ADMIN_PASSWORD_HASH}'

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION_TIME}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION_TIME}
